services:
  course-extractor:
    build: 
      context: .
      args:
        - ENVIRONMENT=${ENVIRONMENT:-development}
    container_name: course-extractor
    ports:
      - "${API_PORT:-8000}:8000"  # FastAPI backend
      - "${FRONTEND_PORT:-5173}:5173"  # Vite frontend
    volumes:
      - ./downloads:/app/downloads
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - ./backend:/app/backend  # For development hot-reload
      - ./frontend:/app/frontend  # For development hot-reload
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - PORT=${API_PORT:-8000}
      - FRONTEND_PORT=${FRONTEND_PORT:-5173}
      - VITE_API_URL=http://localhost:${API_PORT:-8000}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
