services:
  course-extractor:
    build: .
    container_name: course-extractor
    ports:
      - "8000:8000"  # FastAPI backend
      - "5173:5173"  # Vite frontend
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./backend:/app/backend  # For development hot-reload
      - ./frontend:/app/frontend  # For development hot-reload
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - PORT=8000
      - ENVIRONMENT=development # or production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s