services:
  course-extractor:
    build: 
      context: .
      args:
        - ENVIRONMENT=${ENVIRONMENT:-development}
    container_name: course-extractor
    ports:
      - "8000:8000"  # FastAPI backend
      - "5173:5173"  # Vite frontend
    volumes:
      - ./downloads:/app/downloads
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - ./backend:/app/backend
      - ./frontend:/app/frontend
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s