services:
  course-extractor:
    build: 
      context: .
      args:
        - ENVIRONMENT=${ENVIRONMENT:-development}
    container_name: course-extractor
    ports:
      - "8000:8000"  # FastAPI backend
      - "5173:5173"  # Vite frontend
    volumes:
      - ./downloads:/app/downloads
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - ./backend:/app/backend  # For development hot-reload
      - ${ENVIRONMENT:-development}_frontend_volume:/app/frontend
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - API_PORT=8000
      - FRONTEND_PORT=5173
      - ENVIRONMENT=${ENVIRONMENT:-development}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

volumes:
  development_frontend_volume:  # Will be used in development
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/frontend
  production_frontend_volume:  # Empty volume for production
    driver: local