services:
  - type: web
    name: course-extractor
    env: docker
    dockerfilePath: Dockerfile
    branch: main
    plan: starter
    region: us-east-2
    dockerCommand: uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: AWS_ACCESS_KEY_ID
        sync: false  # Set this manually in Render dashboard
      - key: AWS_SECRET_ACCESS_KEY
        sync: false  # Set this manually in Render dashboard
      - key: AWS_BUCKET_NAME
        sync: false  # Set this manually in Render dashboard
      - key: AWS_REGION
        value: us-east-2
